# Spring Boot configuration
spring:
  #profiles:
  #active: development
  application:
    name: agenda
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/agenda
    username: postgres
    password: postgres
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  # RabbitMQ
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  queue:
    name: lembretes
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
    instance:
      preferIpAddress: true
# Server configuration
server:
  port: 8080 #set your port
