# Spring Boot configuration
spring:
  #profiles:
  #active: development
  application:
    name: agenda
  # MongoDB
  data:
    mongodb:
      user: agenda
      password: agenda
      uri: mongodb://host:27017/agenda
# Server configuration
server:
  port: 8080 #set your port
