# Spring Boot configuration
spring:
  #profiles:
  #active: development
  application:
    name: agenda
# Postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/agenda
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  # RabbitMQ
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
  queue:
    name: lembretes
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      fetch-registry: true
      register-with-eureka: true
    instance:
      preferIpAddress: true
# Server configuration
server:
  port: 8080 #set your port
