# Spring Boot configuration
spring:
#profiles:
#active: development
application:
    name: notificacao
# Postgres
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
        datasource:
            platform: postgres
            url: jdbc:postgresql://localhost:5432/notificacao
            username: postgres
            password: postgres
            driverClassName: org.postgresql.Driver
    # RabbitMQ
    rabbitmq:
        addresses: localhost:5672
        username: guest
        password: guest
# Eureka
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
            fetch-registry: true
            register-with-eureka: true
        instance:
            preferIpAddress: true
# RabbitMQ
rabbitmq:
    exchanges:
        internal: internal.exchange
    queues:
        notificacao: notificacao.queue
    routing-keys:
        internal-notification: internal.notificacao.routing-key
# Server configuration
server:
    port: 8081 #set your port

