# Spring Boot configuration
spring:
#profiles:
#active: development
application:
    name: notificacao
    # MongoDB
    data:
        mongodb:
            uri: mongodb://avocat:e296cd9f@localhost:27017
            database: notificacao
    # RabbitMQ
    rabbitmq:
        addresses: localhost:5672
        username: guest
        password: guest
# Eureka
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
            fetch-registry: true
            register-with-eureka: true
        instance:
            preferIpAddress: true
# RabbitMQ
rabbitmq:
    exchanges:
        internal: internal.exchange
    queues:
        notificacao: notificacao.queue
    routing-keys:
        internal-notification: internal.notificacao.routing-key
# Server configuration
server:
    port: 8081 #set your port

